security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_users:
            id: App\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            stateless: false
            provider: app_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
                use_referer: true
                always_use_default_target_path: false
                default_target_path: /books
            logout:
                path: app_logout
                csrf_token_id: logout
                csrf_parameter: _token

    access_control:
        - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: PUBLIC_ACCESS }
        - { path: ^/(login|register|session-test|debug)(/.*)?, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
